### PR TITLE
add #get_stats to Report

### PR DESCRIPTION
**Pull request by moofkit**
- add get_stats method to Report class
- add test

### CODE REVIEW

**Comment by psychocandy** [comment]
@moofkit looks like it's not building.

lgtm - @antlypls any comment?

**Comment by antlypls** [comment]
Code looks good to me.

@psychocandy @miry 
Build failure happens because we test against `1.9.3`, `2.0.0` and `2.1.x`, but minimum required versions for `activesupport` is `2.2.2`.
So we either drop support for those versions, and actually `1.9.3` and `2.0.0` are not maintained anymore. Or we should specify `activesupport` version in `gemspec`.

**Comment by psychocandy** [comment]
@antlypls I suggest we drop support for it and bump the version accordingly.

**Comment by moofkit** [comment]
@antlypls @psychocandy so i need to change travis config and readme. what about gem version?

**Comment by antlypls** [comment]
@moofkit Feel free to change `.travis.yml` in a separate commit. I'd also recommend to update `2.2.x` and `2.3.x` to latest ones.
We'll update gem version before releasing to rubygems.

**Comment by psychocandy** [comment]
👍

**Comment by antlypls** [comment]
👍

**Pull request merged**
