### PR TITLE
Offer set affiliate status

### PR DESCRIPTION
**Pull request by moofkit**
- fix mistyping in `unblockAffiliate` method
- add Offer::setAffiliateApproval method

### CODE REVIEW

**Comment by moofkit** [comment]
guys, any response here?:)

**Comment by miry** [comment]
👍 

@antlypls wdyt?

**Comment by psychocandy** [comment]
👍 let's merge and bump minor version?

**Comment by moofkit** [comment]
@miry @antlypls @psychocandy thanks 🎉

**Pull request merged**
